AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3BucketData:
    Description: s3 bucket for landing and datalake data
    Type: String
    Default: avujic-academy-data
  S3BucketScripts:
    Description: s3 bucket for scripts
    Type: String
    Default: avujic-academy-scripts

Resources:
  AvujicAcademyDataS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketData
      
  AvujicAcademyScriptsS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketScripts